server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://cdb-6z1kjh7u.bj.tencentcdb.com:10217/ceshi?useUnicode=true&characterEncoding=utf8
    username: root
    password: yuanshuai0925
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
  thymeleaf:
    cache: false
  redis:
    host: 39.96.167.196
    password: yuanshuai
    timeout: 2000
    database: 0
    port: 6379

ys:
  security:
    authentication:
      loginPage: /login.html #自定义登录页面
      loginProcessingUrl: /auth/login #登录表单请求路径，默认/login
      usernameParameter: username #自定义前端提交用户名 默认username
      passwordParameter: password #自定义前端提交密码 默认password
      staticPaths: #静态资源/dist/**,/modules/**,/plugins/**
      - /layuimini/**
      - /modules/**
      - /plugins/**
      loginResponseType: JSON #认证之后 响应的类型 ：JSON/REDIRECT
